apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
{{- range $secretKey := .Values.imagePullSecrets }}
- name: {{ $secretKey }}
{{- end }}
metadata:
  name: {{ template "hive-metastore.name" . }}
  labels:
    {{- include "hive-metastore.labels" $ | trim | nindent 4 }}
    {{- include "global.labels" $ | trim | nindent 4 }}
